### ISSUE TITLE
Talk to Octorant

### ISSUE THREAD

**Issue by franzbischoff** [bchanudet/OctoPrint-Octorant#23]
Hi, there is any way to send request commands to Octorant, like with Telegram plugin?

Thanks

**Comment by bchanudet** [comment]
Good evening and thanks for your feedback,

This feature was already asked in #6. You will find out there that for several reasons - one of them being that I'm worried I'll have less and less time to support the plugin if I increase the scope too much - I'm not planning to add such a feature in Octorant.

But! All is not lost, because as you'll be able to see in #21 (another issue mentioning this feature),  apparently @cameroncros has started working on this feature on their side. Depending on how the feature is programmed, maybe it will appear included in Octorant, or as an independent plugin for OctoPrint.

I know this may not be the answer you were wishing for, but I have to manage my limited free time, otherwise I won't even be able to use my own 3D printer any more! 😄 

Best regards

**Comment by franzbischoff** [comment]
Oh, that's ok :)

Thank you


--
Francisco Bischoff


*"O mate está para o gaúcho como o chá para os ingleses, a coca para os
bolivianos, o uísque para os escoceses e o café... para os brasileiros"--
Eduardo Bueno*

On Tue, Apr 24, 2018 at 8:15 PM, Benjamin Chanudet <notifications@github.com
