### ISSUE TITLE
As soon as I enable "Printing Progress" (to every 20 % in this example) it posts INSTANTLY multiple screenshots

### ISSUE THREAD

**Issue by thenixhex311** [bchanudet/OctoPrint-Octorant#71]
Like it is doing a screen shot every second. I would get 'xxx is at 4% over and over and over as discord posts.

Not sure what is going on.
[https://imgur.com/WpuqHlK](url)

**Comment by bchanudet** [comment]
Hi,

Basically, once you start a print, OctoRant starts a "watch" in the background, that every 0.5 second will get the progress status and see if any of the "Progress settings" matches. If so, it will send a message to Discord.

For the timed interval setting, it works like this: every 0.5 second, OctoRant will calculate how many seconds has elapsed since the previous message. If it's more that the number set in the settings, it sends a message. In your case, I see in your screenshot that you have set an interval of 0 second. So OctoRant is trying to send a message every time, because any time interval will be higher than 0.

You also have the same problem with the "Height" set at 0 mm, though here it's a little less problematic as the hotend can spend a long time at the same height. But you'd still receive message for every layer change.

There are two different ways to fix this:
- You can adjust the values to more sensible ones: set a 60 seconds interval to receive an update atleast every minute. As you have the "completion percentage" setting enabled to, if your print reaches a 20% threshold in between two message, you will still receive it. Same for height: set it to 2mm or even more depending on your layers' height and size.
- You can also enable the last setting that is not enabled on your screenshot: the "throttle notifications". If you activate this and set it to e.g. 30 seconds, you won't receive any message if the last one was sent less than 30 seconds ago. It's a good way to limit spam.
